import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import NavComponent from "@/components/navComponent";
import AuthProvider from "./providers/authProvider";
import { ToastContainer } from "react-toastify";
import { getUserByEmail } from "@/lib/actions/actions";
import { getServerSession } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  let user = {};
  if (session?.user?.email) user = await getUserByEmail(session?.user?.email);
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-green-50 h-full`}
      >
        <AuthProvider>
          <HeroUIProvider>
            <NavComponent avatarURL={user?.avatar} />
            {children}
            <ToastContainer />
          </HeroUIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
